name: ci
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      # Add any environment variables needed to run baton-bitbucket-datacenter
      BATON_API_TOKEN: ${{ secrets.BATON_API_TOKEN }}
      BATON_DOMAIN: ${{ secrets.BATON_DOMAIN }}
      BATON_SYNC_CUSTOM_ROLES: true
      # The following parameters are passed to grant/revoke commands
      CONNECTOR_GRANT: 'role:HELP_DESK_ADMIN:assigned:user:00usmetiqnIVpgwmV697'
      # Okta Workflows App Access
      CONNECTOR_ENTITLEMENT: 'role:HELP_DESK_ADMIN:assigned'
      CONNECTOR_PRINCIPAL_TYPE: 'user'
      CONNECTOR_PRINCIPAL: '00usmetiqnIVpgwmV697'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install baton
        uses: conductorone/github-workflows/actions/get-baton@v2
      - name: Build baton-okta-ciam
        run: go build ./cmd/baton-okta-ciam
      - name: Run baton-okta-ciam
        run: ./baton-okta-ciam
      - name: Grant entitlement (even though it probably already exists)
        run: |
          ./baton-okta-ciam --grant-entitlement ${{ env.CONNECTOR_ENTITLEMENT }} --grant-principal ${{ env.CONNECTOR_PRINCIPAL }} --grant-principal-type ${{ env.CONNECTOR_PRINCIPAL_TYPE }}
      - name: Check for grant before revoking
        run: |
          ./baton-okta-ciam && baton grants --entitlement ${{ env.CONNECTOR_ENTITLEMENT }} --output-format=json | jq -e ".grants | any(.principal.id.resource ==\"${{ env.CONNECTOR_PRINCIPAL }}\")"
      - name: Revoke grants
        run: |
          ./baton-okta-ciam --revoke-grant ${{ env.CONNECTOR_GRANT }}
      - name: Check grant was revoked
        run: |
          ./baton-okta-ciam && baton grants --entitlement ${{ env.CONNECTOR_ENTITLEMENT }} --output-format=json | jq -e ".grants | any(.principal.id.resource !=\"${{ env.CONNECTOR_PRINCIPAL }}\")"
      - name: Grant entitlement
        run: |
          ./baton-okta-ciam && ./baton-okta-ciam --grant-entitlement ${{ env.CONNECTOR_ENTITLEMENT }} --grant-principal ${{ env.CONNECTOR_PRINCIPAL }} --grant-principal-type ${{ env.CONNECTOR_PRINCIPAL_TYPE }}
      - name: Check grant was re-granted
        run: |-
          ./baton-okta-ciam && baton grants --entitlement ${{ env.CONNECTOR_ENTITLEMENT }} --output-format=json | jq -e ".grants | any(.principal.id.resource ==\"${{ env.CONNECTOR_PRINCIPAL }}\")"
